services:
  database:
    image: postgres:16
    container_name: database_container
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network
    restart: always
    depends_on:
      - database

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    image: ghcr.io/duckpicker/film-react-nest/backend:latest
    container_name: backend_container
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: ghcr.io/duckpicker/film-react-nest/frontend:latest
    container_name: frontend_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
    restart: always
    depends_on:
      - backend

volumes:
  pg-data:
  pgadmin-data:
  frontend-dist:

networks:
  app-network:
    driver: bridge